openapi: 3.0.3

info:
  title: PsychotechAPI
  version: '0.1'

servers:
  - url: http://localhost:8080/

paths:

 ## Other code
 ##/ ------/

  /clients/new:
    post:
      summary: registration new client
      tags:
        - Clients
      operationId: createNewClient
      requestBody:
        $ref: "./entities.yaml#/components/requestBodies/ClientRegistrationRequest"
      responses:
        '200':
          description: Client created successfully
          content:
            application/json:
              schema:
                $ref: "./entities.yaml#/components/schemas/ClientRegistrationResponse"
        '400':
          $ref: "./entities.yaml#/components/responses/ErrorInfoList"
        '500':
          $ref: "./entities.yaml#/components/responses/ErrorInfoList"

  /recovery/restore_password:
    post:
      summary: restore password from client
      tags:
        - Recovery
      operationId: getClientEmail
      requestBody:
        $ref: "./entities.yaml#/components/requestBodies/ClientEmailFromPasswordRecovery"
      responses:
        '200':
          description: Mail created successfully
          content:
            application/json:
              schema:
                $ref: "./entities.yaml#/components/schemas/AuthResponse"
        '400':
          $ref: "./entities.yaml#/components/responses/ErrorInfoList"
        '500':
          $ref: "./entities.yaml#/components/responses/ErrorInfoList"